#!/bin/bash

#load functions and variables
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Check if connected to internet
while [[ "$(wget -q --spider http://google.com)" -eq 1 ]]
do
  echo "I couldn't detect an internet connection! Trying again..."
  sleep 2
done

#If loop ends, User online
#Main
if [ "$(cat '$PW_PREFIX/share/pi-ware/version')" != "$LAST_COMMIT" ]; then
  python3 $HOME/pi-ware/func/update/update.py
  exit 0
else
  echo "Pi-ware is currently Up-To-Date"
  exit 1
fi
