#!/bin/bash

#Variables
AppName="APTCleaner"
AppLocation="Menu > System > $AppName"
RepoUrl="https://github.com/RP400/CryApp"
export PW_PREFIX="$HOME/.local/share/pi-ware"
PACMANG="$(cat $PW_PREFIX/inst-pref)"
fwe=""
ers=""

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  sleep 2
  if [ "$2" == "exit" ]; then
    exit 1
  else
    fwe="1"
    ers+="$1"
  fi
}

function warning {
  echo -e "\e[91m$2\e[39m"
  sleep "$1"
}

#Main
sudo $PACKMANG yad
sudo $PACKMANG git
cd "$HOME" #find home directory
git clone https://github.com/GabeCoder/aptcleaner
cd "aptcleaner"
chmod +x autostart.sh
chmod +x aptcleaner.sh
chmod +x clean.sh
echo "[Desktop Entry]
Type=Application
Name=APT Cleaner
Comment=Package remover for Debian
Exec="${HOME}/aptcleaner/aptcleaner.sh"
Icon="${HOME}/aptcleaner/icon.png"
Terminal=false
Categories=System;" > aptcleaner.desktop
desktop-file-install --dir="$HOME"/.local/share/applications aptcleaner.desktop
echo "[Desktop Entry]
Type=Application
Name=APT Cleaner
Comment=Package remover for Debian
Exec="${HOME}/aptcleaner/autostart.sh"
Icon="${HOME}/aptcleaner/icon.png"
Terminal=false
Categories=System;" > aptcleaner.desktop
desktop-file-install --dir="$HOME"/.config/autostart aptcleaner.desktop

#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  sleep 1
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully installed $AppName. You can find it in %AppLocation."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
