#!/bin/bash


#Variables
PW_PREFIX="$HOME/.local"
fwe=""
ers=""

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  if [ "$2" == "exit" ]; then
    exit 1
  else
    fwe="1"
    ers+="$1"
  fi
}

function warning {
  echo -e "\e[91m$2\e[39m"
  sleep "$1"
}

#Make required directory for updater
mkdir -p "$PW_PREFIX/share/pi-ware"
mkdir -p "$PW_PREFIX/bin"
echo $(git rev-parse main) > "$PW_PREFIX/share/pi-ware/version"

if [ "$1" == "update" ];then
  rm -rf $HOME/pi-ware
  cp -r "$PW_PREFIX/share/pi-ware/updater_files" $HOME/pi-ware
  cp -r $HOME/pi-ware/store.py "$PW_PREFIX/bin/pi-ware"
  chmod +x "$PW_PREFIX/bin/pi-ware"
else
  echo "Installing pi-ware..."
fi

#Main
echo "Creating a desktop entry for Pi-Ware..."
sudo mkdir -p $HOME/.local/share/applications
echo "[Desktop Entry]
Name=Pi-Ware
Comment=Raspberry Pi app store
Exec=python3 $HOME/pi-ware/store.py
Icon=$HOME/pi-ware/icons/logo.png
Categories=Utility;
Type=Application
Terminal=false" > $HOME/.local/share/applications/pi-ware.desktop
echo "Creating an auto updater for Pi-Ware..."
mkdir -p /etc/systemd/system/
echo "[Unit]
Description=Auto update service for pi-ware
After=network.target

[Service]
ExecStart=/usr/bin/bash auto-update
WorkingDirectory=$HOME/pi-ware
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target" > /dev/null | sudo tee /etc/systemd/system/Auto-update-pi-ware.service
sudo systemctl enable Auto-update-pi-ware.service
#install lxterminal if it is not alreadt installed
if ! command -v lxterminal >/dev/null;then
  echo "Installing LXTerminal..."
  if [ -f /usr/bin/apt ];then
    echo "Package manager is: apt"
    sudo apt update
    sudo apt install lxterminal -y || error "Failed to install lxterminal."
  elif [ -f /usr/bin/pacman ];then
    echo "Package manager is: pacman"
    sudo pacman -S lxterminal || error "Failed to install lxterminal;."
  else
    error "Failed to find any package manager to install lxterminal."
  fi
fi
#Set package manager
if [ -f /usr/bin/apt ];then
  echo "Package manager is: apt"
  echo "apt-get" > "$PW_PREFIX/share/pi-ware/inst-pref"
elif [ -f /usr/bin/pacman ];then
  echo "Package manager is: pacman"
  echo "pacman -S" > "$PW_PREFIX/share/pi-ware/inst-pref"
else
  error "Failed to find any package manager to install lxterminal."
fi
echo "Done!"
echo "You can find Pi-Ware in Menu > Accessories > Pi-Ware."
