#!/bin/bash

echo "Creating a desktop entry for Pi-Ware..."
sleep 2s
mkdir -p $HOME/.local/share/applications
echo "[Desktop Entry]
Name=Pi-Ware
Comment="Raspberry Pi app store"
Exec=sudo python3 $HOME/pi-ware/store.py
Icon=$HOME/pi-ware/icon.png
Categories=Utility;
Type=Application
Terminal=false" > $HOME/.local/share/applications/pi-ware.desktop
sleep 1s
echo "Done!"
echo "You can find Pi-Ware in Menu > Accessories > Pi-Ware."
sleep 2s
