#!/bin/bash

#Check what arg was passed
#$1 is usualy left blank

if [ "$1" == "update" ]; then
  #Run update script
elif [ "$1" == "store" ]; then
  #Run store.py
  python3 $HOME/pi-ware/store.py
else
  #Inform user an unkown arg was passed
  echo "ERROR: Unkown argument '$1'"
fi
