#!/bin/bash

#Variables
fwe=""
ers=""

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  if [ "$2" == "exit" ]; then
    exit 1
  else
    fwe="1"
    ers+="$1"
  fi
}

function warning {
  echo -e "\e[91m$2\e[39m"
  sleep "$1"
}

#Main
echo "Uninstalling Pi-Ware"
#Remove pi-ware utility
rm -rf $HOME/.local/bin/pi-ware || error "Unable to remove $HOME/.local/bin/pi-ware"
#Remove pi-ware desktop entry
rm -rf $HOME/.local/share/applications/pi-ware.desktop || error "Unable to remove $HOME/.local/share/applications/pi-ware.desktop"
#Remove pi-ware auto-updater
rm -rf $HOME/.config/autostart/update-pi-ware.desktop || error "Unable to remove $HOME/.config/autostart/update-pi-ware.desktop"
#Remove pi-ware update-files
rm -rf $HOME/.local/share/pi-ware || error "Unable to remove $HOME/.local/share/pi-ware"
#Remove Pi-Ware's folder
rm -rf $HOME/pi-ware || error "Unable to remove $HOME/pi-ware"

#Inform user that the uninstall has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully uninstalled pi-ware."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
