#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Main
echo "Uninstalling Pi-Ware"
#Remove pi-ware utility
echo "Removing Pi-Ware from terminal"
rm -rf $HOME/.local/bin/pi-ware || error "Unable to remove $HOME/.local/bin/pi-ware"
#Remove pi-ware desktop entry
echo "Removing Pi-Ware from applications"
rm -rf $HOME/.local/share/applications/pi-ware.desktop || error "Unable to remove $HOME/.local/share/applications/pi-ware.desktop"
#Remove pi-ware desktop entry, on the desktop
echo "Removing Pi-Ware from applications"
rm -rf $HOME/Desktop/pi-ware.desktop || error "Unable to remove $HOME/Desktop/pi-ware.desktop"
#Remove pi-ware settings desktop entry
echo "Removing Pi-Ware Settings from applications"
rm -rf $HOME/.local/share/applications/pi-ware-settings.desktop || error "Unable to remove $HOME/.local/share/applications/pi-ware-settings.desktop"
#Remove pi-ware auto-updater
echo "Removing Pi-Ware auto-updater"
rm -rf $HOME/.config/autostart/update-pi-ware.desktop || error "Unable to remove $HOME/.config/autostart/update-pi-ware.desktop"
#Remove saved pi-ware info
echo "Removing Pi-Ware updater files..."
rm -rf $HOME/.local/share/pi-ware || error "Unable to remove $HOME/.local/share/pi-ware"
#Remove Pi-Ware's folder
echo "Removing Pi-Ware folder..."
rm -rf $HOME/pi-ware || error "Unable to remove $HOME/pi-ware"

#Inform user that the uninstall has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully uninstalled pi-ware."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
