#!/bin/bash


#Variables
PW_PREFIX="$HOME/.local/share/pi-ware"
PW_REPO="https://github.com/zachthecoder14/pi-ware.git"
LAST_COMMIT="$(git ls-remote "$PW_REPO" | grep refs/heads/main | cut -f 1)"

#Main
if [ "$(cat "$PW_PREFIX/version")" != "$LAST_COMMIT" ]; then
  echo "Updating Pi-Ware..."
  cd "$PW_PREFIX"
  ls
  sudo rm -rf updater_files
  ls
  git clone "$PW_REPO" updater_files
  ls
  #rm -rf $HOME/pi-ware
  cp -r "$PW_PREFIX/share/pi-ware/updater_files" $HOME/pi-ware1
  cp -r $HOME/pi-ware1/store.py "$PW_PREFIX/bin/pi-ware"
  chmod +x "$PW_PREFIX/bin/pi-ware"
  cd ..
  echo "Update complete."
  exit 0
else
  echo "Pi-Ware is currently up-to-date."
  exit 1
fi
