#!/bin/bash

#Variables
PW_PREFIX="$HOME/.local/share"
PW_REPO="https://github.com/zachthecoder14/pi-ware.git"
LAST_COMMIT="$(git ls-remote "$PW_REPO" | grep refs/heads/main | cut -f 1)"

#Main
if [ "$(cat "$PW_PREFIX/pi-ware/version")" != "$LAST_COMMIT" ] || [ "$1" == force ]; then
  if [ "$1" == force ]; then
    echo "Force updating pi-ware"
  else
    echo "Updating Pi-Ware..."
  fi
  cd "$PW_PREFIX/pi-ware"
  ls
  sudo rm -rf updater_files
  ls
  git clone "$PW_REPO" updater_files
  ls
  cd updater_files
  ls
  cp -r "$PW_PREFIX/pi-ware/updater_files" $HOME/pi-ware
  #cp -r $HOME/pi-ware/store.py "$PW_PREFIX/bin/pi-ware"
  #chmod +x "$PW_PREFIX/bin/pi-ware"
  cd ..
  echo "Update complete."
  exit 0
else
  echo "Pi-Ware is currently up-to-date."
  exit 1
fi
