#!/bin/bash
cd /home/pi/pi-ware
mkdir updater_files
cd updater_files/
git clone https://github.com/zachthecoder14/pi-ware.git
cd pi-ware/
rsync * ../../
rsync -r * ../../
cd ../../
sudo rm -r updater_files/
clear
echo "Update complete."
sleep 2s
