#!/bin/bash

export PW_PREFIX="$HOME/.local"
export PW_REPO="https://github.com/zachthecoder14/pi-ware.git"
export LAST_COMMIT="$(git ls-remote "$PW_REPO" | grep refs/heads/main | cut -f 1)"

if [[ "$(cat "$PW_PREFIX/share/pi-ware/version")" != "$LAST_COMMIT" ]]; then
	echo "Updating Pi-Ware..."
	cd "$PW_PREFIX/share/pi-ware"
	rm -rf ./apps
	mkdir -p ./updater_files
	git clone "$PW_REPO" ./updater_files
	cd ./updater_files
	chmod a+x ./install
	./install update
	cd ../
	sudo rm -rf ./updater_files
	echo "Update complete."
	exit 0
else
	echo "Pi-Ware is currently up-to-date."
	exit 1
fi
