#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Local Variables
version="3.1.2"
serverurl="http://pi-ware-telemetry.ml/uploaded/webcord-3.1.2-armv7l.App-2.appimage"

#Main
cd $HOME
echo "Downloading: Webcord $version"
curl "$serverurl" --output "webcord-$version-$aarch.AppImage"
echo "[Desktop Entry]
Name=Webcord
Comment=A Discord client for arm devices
Exec="./$HOME/webcord-$version-$aarch.AppImage"
Icon="$HOME/pi-ware/apps/webcord/icon.png"
Categories=Utility;
Type=Application
Terminal=false" > "$PW_APPS/webcord-$version-$aarch.desktop"
