#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Local Variables
AppName="Webcord"
version="3.1.3"
serverurl="http://pi-ware-telemetry.ml/uploaded/webcord-$version-armv7l.AppImage"
AppLocation="Menu > Accessories > Webcord"

#Main
cd $HOME
echo "Downloading: Webcord $version"
curl "$serverurl" --output "$HOME/webcord-$version.AppImage"
echo "[Desktop Entry]
Name=Webcord
Comment=A Discord client for arm devices
Exec=".$HOME/webcord-$version.AppImage"
Icon="$HOME/pi-ware/apps/Webcord/icon.png"
Categories=Utility;
Type=Application
Terminal=false" > "$PW_APPS/webcord-$version.desktop"
#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  sleep 1
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully installed $AppName. You can find it in $AppLocation."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
