#!/bin/bash

#Variables
PW_PREFIX="$HOME/.local/share"
PW_REPO="https://github.com/zachthecoder14/pi-ware.git"
LAST_COMMIT="$(git ls-remote "$PW_REPO" | grep refs/heads/main | cut -f 1)"

#Main
if [ "$(cat "$PW_PREFIX/pi-ware/version")" != "$LAST_COMMIT" ]; then
  python3 $HOME/pi-ware/func/update.py
  exit 0
else
  exit 1
fi
