#!/bin/bash

#Variabels
#Keep the line below if you modify or change any part of this code!
OG_Creator="oxmc"
#Year this program was made.
OG_Year="2021"
#Get current year.
Year="$(date +'%Y')"
#Get the current date.
todaydate="$(date +'%A,%B,%d,%Y')"
#Prgram version
VER="1.4"
#Program name
AppName="Pi-Ware-Term"

#load functions
source "$HOME/pi-ware/func/api" || error "failed to source $HOME/pi-ware/func/api"

#Main
#Check if OG_Year and Year are the same.
if [[ "$OG_Year" -eq "$Year" ]]; then
  #CopyYear is OG_Year
  CopyYear="$OG_Year"
else
  #CopyYear is OG_Year + Year
  CopyYear="$OG_Year - $Year"
fi

#Check if pi-ware is installed
if [ ! -d "$HOME/pi-ware" ]; then
  error "Pi-Ware needs to be installed to use this." exit
fi

# flags. default is to launch app.
if [[ "$1" == "--version" ]] || [[ "$1" == "-v" ]]; then
  echo -e "
  $(tput setaf 9)###############################################################
  $(tput setaf 9)# $(tput setaf 4)$(tput bold)$AppName version $VER by $OG_Creator & The Pi-Ware-Team | $CopyYear $(tput sgr 0)$(tput setaf 9) #
  $(tput setaf 9)###############################################################$(tput sgr 0)
  "
  exit 0
elif [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
  echo -e "
    $(tput setaf 6)$(tput bold)USAGE:$(tput sgr 0)
    $(tput bold)intended usage:$(tput sgr 0)
    --install [AppName] | Install an app from pi-ware. 'pi-ware --install CryApp' installs CryApp to your system.
    --uninstall [AppName] | Uninstalls an app from pi-ware. 'pi-ware --uninstall CryApp' uninstalls CryApp from your system.
    --uninstall-all | Uninstalls pi-ware from your system completly.
    --update | Checks if pi-ware is up-to-date, if you want to force update pi-ware run 'pi-ware --update force'.
    --apps | List all availible apps in pi-ware.
    $(tput setaf 6)$(tput bold)Extra commands that have no use:$(tput sgr 0)
    --version or -v | print version and exit.
    --help or -h | print this help and exit.
    --author | print who made this and exit.
  "
  exit 0
elif [[ "$1" == "--author" ]]; then
  echo -e "$(tput setaf 6)$(tput bold)Author of $AppName:$(tput sgr 0) $OG_Creator"
  echo -e "$(tput setaf 6)$(tput bold)Author of Pi-Ware:$(tput sgr 0) ZachTheCoder14"
  exit 0
elif [[ "$1" == "--install" ]]; then
  if [[ "$2" != "" ]]; then
    echo -e "
    $(tput setaf 9)###############################################################
    $(tput setaf 9)# $(tput setaf 4)$(tput bold)$AppName version $VER by $OG_Creator & The Pi-Ware-Team | $CopyYear $(tput sgr 0)$(tput setaf 9) #
    $(tput setaf 9)###############################################################$(tput sgr 0)
    "
    echo "Installing $2"
    echo "To quit at any time press CTRL + C"
    bash "$HOME/pi-ware/apps/$2/install"
  else
    error "ERROR: AppName not provided."
    echo "pi-ware --install AppName | for help run 'pi-ware --help'"
  fi
elif [[ "$1" == "--uninstall" ]]; then
  if [[ "$2" != "" ]]; then
    echo -e "
    $(tput setaf 9)###############################################################
    $(tput setaf 9)# $(tput setaf 4)$(tput bold)$AppName version $VER by $OG_Creator & The Pi-Ware-Team | $CopyYear $(tput sgr 0)$(tput setaf 9) #
    $(tput setaf 9)###############################################################$(tput sgr 0)
    "
    echo "Uninstalling $2"
    echo "To quit at any time press CTRL + C"
    bash "$HOME/pi-ware/apps/$2/uninstall"
  else
    error "ERROR: AppName not provided."
    echo "pi-ware --uninstall AppName | for help run 'pi-ware --help'"
  fi
elif [[ "$1" == "--update" ]]; then
  echo -e "
  $(tput setaf 9)###############################################################
  $(tput setaf 9)# $(tput setaf 4)$(tput bold)$AppName version $VER by $OG_Creator & The Pi-Ware-Team | $CopyYear $(tput sgr 0)$(tput setaf 9) #
  $(tput setaf 9)###############################################################$(tput sgr 0)
  "
  echo "Checking for updates..."
  echo "To quit at any time press CTRL + C"
  bash "$HOME/pi-ware/updater"
elif [[ "$1" == "--uninstall-all" ]]; then
  echo "Uninstalling pi-ware from your system..."
  bash "$HOME/pi-ware/uninstall"
  rm -rf $HOME/.local/bin/pi-ware
  echo "Successfully uninstalled pi-ware from your system!"
else
  error "ERROR: $AppName requires a valid command! | for help run 'pi-ware --help'"
  pi-ware --help
  exit 1
fi
