#!/bin/bash

#This file uploads a app telemetry file to http://pi-ware-telemetry.ml/

#load functions and variables
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Check if connected to internet
while [[ "$(wget -q --spider http://google.com)" -eq 1 ]]
do
  echo "I couldn't detect an internet connection! Trying again..."
  sleep 2
done

#If loop ends, User online
#Check if user allowed telemetry
if [ "$(cat $PW_DATA/telemetry)" == "True" ]; then
  echo "Telemetry allowed"
  echo "Checking for telemetry file..."
  if [ -f "$PW_DATA/telemetry/data-1.json" ]; then
    echo "Sending file..."
    curl -F "fileToUpload=@$PW_DATA/telemetry/data-1.json" http://pi-ware-telemetry.ml/uploader.php | echo "ERROR: I was unable to send the telemetry file."
  else
    logname="$todaydate-$currenttime-telemetry.log"
    echo "ERROR: Unable to find '$PW_DATA/telemetry/data.json'" > "$PW_LOGS/$logname"
    error "ERROR: Unable to find '$PW_DATA/telemetry/data.json'\nA log has been generated in: '$HOME/pi-ware/logs/$logname'"
  fi
else
  echo "Telemetry not allowed"
  error "ERROR: Unable to send a telemetry file as user selected 'False' to send telemetry."
fi
