#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || error "failed to source $HOME/pi-ware/func/api"

if [ -f "$PW_PREFIX/inst-pref" ]; then
  echo "Your package manager is: $PACMANG"
  echo "Uninstalling $1"
  echo $PASSWD | sudo -S bash $HOME/pi-ware/apps/$1/uninstall
  sleep 2
else
  echo "Your package manager is: $PACMANG"
  echo "Unable to locate '$PW_PREFIX/inst-pref', please contact staff at pi-ware discord"
  sleep 4
fi
