#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Local Variables
AppName="Pi-Apps"
AppLocation="Menu > Accessories > $AppName"

#Main
warning 5 "Warning: Uninstall $AppName will remove any saved data associated with $AppName. /n To cancel press CTRL + C in the next 5 seconds."
echo "Uninstalling $AppName:"
cd ~/pi-apps || error "Unable to cd to ~/pi-apps, does it exist?" exit
bash uninstall || error "Unable to execute ~/pi-apps/uninstall, does it exist?" exit
#Inform user that the uninstall has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  sleep 1
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully installed $AppName. You can find it in $AppLocation."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
