#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Local Variables
AppName="DollarSkip"
version="3.1.3"
serverurl="https://raw.githubusercontent.com/CleanMachine1/DollarSkip/master/install.sh"
AppLocation="Terminal"

#Main
cd $HOME
echo "Downloading $AppName"
curl "$serverurl" --output "$HOME/$AppName-install.sh"
bash "$HOME/$AppName-install.sh" || error "Failed to run '$HOME/$AppName-install.sh'" exit
#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  sleep 1
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully installed $AppName. You can find it in $AppLocation."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
