#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || error "failed to source $HOME/pi-ware/func/api"

if [ -f "$PW_PREFIX/share/pi-ware/inst-pref" ]; then
  echo "Your package manager is: $PACMANG"
  echo "Installing $1"
  bash $HOME/pi-ware/apps/$1/install
  sleep 2
else
  echo "Your package manager is: $PACMANG"
  echo "Unable to locate '$PW_PREFIX/share/pi-ware/inst-pref', please contact staff at pi-ware discord"
  sleep 4
fi
