#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Local Variables
AppName="CryApp"
AppLocation="Menu > Accessories > $AppName"
RepoUrl="https://github.com/RP400/CryApp"

#Main
#Clone repo
cd $HOME
git clone $RepoUrl|| error "Unable to clone ${AppName}'s repo!" exit
#Cd into repo
cd $HOME/CryApp/Pi-Ware/CryApp || error "Unable to cd into ${AppName}!"
#Install dependencies
pip3 install mcpi
pip3 install guizero
#Install app
mv $HOME/CryApp/CryApp $HOME/.local/share/applications/ || error 'Failed to move application' 
#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  sleep 1
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully installed $AppName. You can find it in $AppLocation."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
