#!/bin/bash

#Script created by oxmc
#Made for Lunar-Client by gl91306

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  if [ "$2" == "exit" ]; then
    exit 1
  else
    fwe="1"
    ers+="$1"
  fi
}

function warning {
  echo -e "\e[91m$2\e[39m"
  sleep "$1"
}

#Variables
export PW_PREFIX="$HOME/.local/share/pi-ware"
PACMANG="$(cat $PW_PREFIX/inst-pref)"
fwe="0"
ers=""

#Main
#install modprobe if not already installed
if ! command -v modprobe >/dev/null;then
   sudo $PACKMANG modprobe
fi

#Run modprobe fuse
sudo modprobe fuse

cd $HOME
#Download client
wget https://github.com/gl91306/lunar/raw/master/lunarclient-2.7.3b-armv7l.AppImage

if [ ! -d ~/lwjgl3arm32 ]; then
    mkdir ~/lwjgl3arm32
fi
if [ ! -d ~/lwjgl2arm32 ]; then
    mkdir ~/lwjgl2arm32
fi
if [ ! -f jdk-8u251-linux-arm32-vfp-hflt.tar.gz ]; then
    wget https://github.com/mikehooper/Minecraft/raw/main/jdk-8u251-linux-arm32-vfp-hflt.tar.gz
fi
if [ ! -f jdk-16.0.1+9-jre.tar.gz ]; then
    wget https://github.com/gl91306/lunar/raw/master/jdk-16.0.1%2B9-jre.tar.gz
fi
if [ ! -f lwjgl3arm32.tar.gz ]; then
    wget https://github.com/mikehooper/Minecraft/raw/main/lwjgl3arm32.tar.gz
fi
if [ ! -f lwjgl2arm32.tar.gz ]; then
    wget https://github.com/mikehooper/Minecraft/raw/main/lwjgl2arm32.tar.gz
fi
if [ ! -d /opt/jdk ]; then
    sudo mkdir /opt/jdk
fi

sudo tar -zxf jdk-8u251-linux-arm32-vfp-hflt.tar.gz -C /opt/jdk
sudo tar -zxf jdk-16.0.1+9-jre.tar.gz -C /opt/jdk
tar -zxf lwjgl3arm32.tar.gz -C ~/lwjgl3arm32
tar -zxf lwjgl2arm32.tar.gz -C ~/lwjgl2arm32
sudo update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_251/bin/java 0
sudo update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_251/bin/javac 0
sudo update-alternatives --set java /opt/jdk/jdk1.8.0_251/bin/java
sudo update-alternatives --set javac /opt/jdk/jdk1.8.0_251/bin/javac
cd lwjgl2arm32
wget https://github.com/gl91306/lunar/raw/master/libwebp-imageio32.so
cd
cd lwjgl3arm32
wget https://github.com/gl91306/lunar/raw/master/libwebp-imageio32.so
cd
cd /opt/jdk/opt/jdk
sudo cp -r jdk-16.0.1+9-jre /opt/jdk
cd /opt/jdk
sudo rm -rf opt
cd
cd /opt/jdk/jdk1.8.0_251
sudo rm -rf jre
echo please wait a bit, as this step takes a bit
sudo apt-get install subversion
sudo svn checkout https://github.com/gl91306/lunar/trunk/jre
cd
sudo apt-get install unzip
wget https://github.com/gl91306/lunar/raw/master/javafx-sdk-17.zip
unzip javafx-sdk-17.zip -d /home/pi/Desktop
cd
#Change perms of Launcher
sudo chmod +x $HOME/lunarclient-2.7.3b-armv7l.AppImage

cd
rm -rf jdk-8u251-linux-arm32-vfp-hflt.tar.gz
rm -rf jdk-16.0.1+9-jre.tar.gz
rm -rf javafx-sdk-17.zip
rm -rf lwjgl2arm32.tar.gz
rm -rf lwjgl3arm32.tar.gz

#Add icon
cd
mkdir lunarassets
cd lunarassets
wget https://github.com/gl91306/lunar/raw/master/lunarclient.png
cd

#Then make menu button & desktop icon
echo "Creating a desktop entry for Lunar-Client..."
echo "[Desktop Entry]
Name=Lunar Client
Comment=Lunar Client for Rpi made by PiKATchu on Discord.
Exec=$HOME/lunarclient-2.7.3b-armv7l.AppImage
Icon=$HOME/lunarassets/lunarclient.png
Categories=Game;
Type=Application
Terminal=false" > "$HOME/.local/share/applications/Lunar-Client.desktop"
echo "Adding desktop shortcut..."
cp $HOME/.local/share/applications/Lunar-Client.desktop $HOME/Desktop

#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully installed Lunar Client. You can find it in Menu > Games > Lunar Client."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
