#!/bin/bash

#Script created by oxmc
#Made for Lunar-Client by gl91306

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  if [ "$2" == "exit" ]; then
    exit 1
  else
    fwe="1"
    ers+="$1"
  fi
}

function warning {
  echo -e "\e[91m$2\e[39m"
  sleep "$1"
}


#Variables
fwe="0"
ers=""

#Main

#Cd into home dir
cd $HOME

#Remove Lunar-Client folder
Sudo rm -rf $HOME/.lunarclient || error "unable to remove $HOME/.lunarclient!"

#Remove AppImage
Sudo rm -rf $HOME/lunarclient-2.7.0-armv7l.AppImage || error "Unable to remove $HOME/lunarclient-2.7.0-armv7l.AppImage!"

rm -rf lunarclient-2.7.3b-armv7l.AppImage
rm -rf lunarclient-2.7.3a-armv7l.AppImage
rm -rf lunarclient-2.7.2-armv7l.AppImage
rm -rf lunarclient-2.7.0-armv7l.AppImage

rm -rf '$HOME/Desktop/Lunar Client'
rm -rf "$HOME/.local/share/applications/Lunar-Client.desktop"

#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Finished!"
  exit 0
fi
