#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || error "failed to source $HOME/pi-ware/func/api"

#Main
echo "Starting first use..."
python3 $HOME/pi-ware/func/firstuse/setup.py
echo "Update pi-ware.desktop"
echo "False" > "$PW_PREFIX/share/pi-ware/firstrun"
echo "[Desktop Entry]
Name=Pi-Ware
Comment=Raspberry Pi app store (Happy Holidays!)
Exec=python3 $HOME/pi-ware/store/main.py
Icon=$HOME/pi-ware/icons/logo-full-christmas.png
Categories=Utility;
Type=Application
Terminal=false" > $HOME/.local/share/applications/pi-ware.desktop
#Copy to desktop
cp -r $HOME/.local/share/applications/pi-ware.desktop $HOME/Desktop/pi-ware.desktop
