#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || error "failed to source $HOME/pi-ware/func/api"

#Main
echo "Starting first use..."
python3 $HOME/pi-ware/func/firstuse/setup.py
echo "Update pi-ware.desktop"
echo "False" > "$PW_PREFIX/share/pi-ware/firstrun"
if [ "$month" -eq "12" ]; then
  echo "christmas logo"
  logo="$HOME/pi-ware/icons/logo-full-christmas.png"
  comment="Raspberry Pi app store (Happy holidays!)"
else
  logo="$HOME/pi-ware/icons/logo.png"
  comment="Raspberry Pi app store"
fi
echo "[Desktop Entry]
Name=Pi-Ware
Comment="$comment"
Exec=python3 $HOME/pi-ware/store/main.py
Icon=$logo
Categories=Utility;
Type=Application
Terminal=false" > $HOME/.local/share/applications/pi-ware.desktop
#Copy to desktop
cp -r $HOME/.local/share/applications/pi-ware.desktop $HOME/Desktop/pi-ware.desktop
