#!/bin/bash

export PW_PREFIX="$HOME/.local/share/pi-ware"
PACKMANG="$(cat $PW_PREFIX/inst-pref)"


sudo apt-get remove -y minecraft-pi-reborn-client || true
sudo apt-get remove -y gmcpil || true
sudo apt-get remove -y jmcpil || true
