#!/bin/bash

##########################################################
# script by Itai-Nelken - https://github.com/Itai-Nelken #
##########################################################

echo "Uninstalling Firefox..."

sudo apt purge firefox -y
sudo rm /etc/apt/preferences.d/99bionic-updates
sudo rm /etc/apt/sources.list.d/ubuntu.list
sudo apt-key del 3B4FE6ACC0B21F32

clear
echo """Successfully uninstalled Firefox.
Closing in 5 seconds."""
sleep 5s