#!/bin/bash

#Variables
AppName="Mari0"
AppLocation="Menu > games > $AppName"
RepoUrl="https://github.com/IsaacMvmv/Mari0_rpi"
export PW_PREFIX="$HOME/.local/share/pi-ware"
PACMANG="$(cat $PW_PREFIX/inst-pref)"
fwe=""
ers=""

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  if [ "$2" == "exit" ]; then
    exit 1
  else
    fwe="1"
    ers+="$1"
  fi
}

function warning {
  echo -e "\e[91m$2\e[39m"
  sleep "$1"
}

#Main
echo "Installing $AppName"
#Clone repo
git clone $RepoUrl || error "Unable to clone ${AppName}'s repo!" exit
#Cd into repo
cd $AppName || error "Unable to cd into ${AppName}!"
#change perms
chmod +x launch.sh love_armhf/love
#Install dependencies based on package manager
if [ -f /usr/bin/apt ];then
  dependencies="libc6 libfreetype6 libgcc1 libluajit-5.1-2 libmodplug1 libmpg123-0 libogg0 libopenal1 libsdl2-2.0-0 libstdc++6 libtheora0 libvorbisfile3 zlib1g"
elif [ -f /usr/bin/pacman ];then
  dependencies="--needed desktop-file-utils freetype2 hicolor-icon-theme libmodplug libtheora libvorbis luajit mpg123 openal sdl2 shared-mime-info"
else
  error "Failed to find any package manager."
fi
sudo $PACKMANG 'install' '$dependencies'
#Make menu button
echo "Creating a desktop entry for ${Appame}..."
mkdir -p $HOME/.local/share/applications
echo "[Desktop Entry]
Name=$AppName
Comment=Mario's classic game but with coop multiplayer and portals!
Exec=bash $HOME/Mari0_rpi/launch.sh
Icon=$HOME/Mari0_rpi/mari0.png
Categories=Games;
Type=Application
Terminal=false" > $HOME/.local/share/applications/$AppName.desktop

#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully installed $AppName. You can find it in %AppLocation."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
