#!/bin/bash

#Variables
AppName="Mari0"
export PW_PREFIX="$HOME/.local/share/pi-ware"
PACMANG="$(cat $PW_PREFIX/inst-pref)"
fwe="0"
ers=""

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  if [ "$2" == "exit" ]; then
    exit 1
  else
    fwe="1"
    ers+="$1"
  fi
}

function warning {
  echo -e "\e[91m$2\e[39m"
  sleep "$1"
}

#Main
#Uninstall dependencies
if [ -f /usr/bin/apt ]; then
  sudo apt remove love
elif [ -f /usr/bin/pacman ]; then
  sudo pacman -Rs love
fi

#Clean up dirs
rm -rf /opt/Mari0_rpi
rm -rf $HOME/Mari0

#Remove desktop entrys
rm -rf $HOME/.local/share/applications/$AppName.desktop

#Inform user that the uninstall has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully uninstalled $AppName."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
