#!/bin/bash

#load functions
source "$HOME/pi-ware/func/api" || echo "failed to source $HOME/pi-ware/func/api"

#Local Variables
AppName="Pi-Apps"
AppLocation="Menu > Accessories > $AppName"

#Main
echo "Uninstalling Pi-Apps:"
cd ~/pi-apps
bash uninstall
sudo rm -rf "$PW_APPS/pi-apps/pi-apps.desktop"
#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  sleep 1
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Successfully installed $AppName. You can find it in $AppLocation."
  echo "Closing in 5 seconds."
  sleep 5s
  exit 0
fi
