#!/bin/bash

#Script created by oxmc
#Made for Lunar-Client by gl91306

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  if [ "$2" == "exit" ]; then
    exit 1
  else
    fwe="1"
    ers+="$1"
  fi
}

function warning {
  echo -e "\e[91m$2\e[39m"
  sleep "$1"
}

#Variables
fwe=""
ers=""

#Main
#install modprobe if not already installed
if ! command -v modprobe >/dev/null;then
  
  if [ -f /usr/bin/apt ];then
    sudo apt update
    sudo apt install -y modprobe || echo "Failed to install modprobe."
  else
    error "Failed to find any package manager to install modprobe."
  fi
fi

#Run modprobe fuse
sudo modprobe fuse

#Download client
wget https://github.com/gl91306/lunar/blob/master/lunarclient-2.7.0-armv7l.AppImage?raw=true

#Change perms of Launcher
sudo chmod +x ~/lunarclient-2.7.0-armv7l.AppImage

#Run launcher
~/lunarclient-2.7.0-armv7l.AppImage

#Handle error about jvm
#Copy jdk version into ~/.lunarclient/jre/zulu8.52.0.23-ca-fx-jre8.0.282-linux_x64
sudo cp /opt/jdk/jdk1.8.0_251/jre ~/.lunarclient/jre/zulu8.52.0.23-ca-fx-jre8.0.282-linux_x64

#Then make menu button
echo "Creating a desktop entry for Lunar-Client..."
echo "[Desktop Entry]
Name=\"Lunar-Client for Rpi\"
Comment=\"Lunar-Client for Rpi made by PiKATchu on Discord.\"
Exec=~/lunarclient-2.7.0-armv7l.AppImage
Icon=~/.lunarclient/icon.png
Categories=Utility;
Type=Application
Terminal=false" > "~/.local/share/applications/Lunar-Client.desktop"

#Inform user that the install has finished
#Check if finished with errors
if [ "${fwe}" == "1" ]; then
  echo "This script finished with errors, Here are the errors: ${ers}"
  exit 1
elif [ "${fwe}" == "0" ]; then
  echo "Finished!"
  exit 0
fi